dist: trusty
sudo: required
services:
- docker
addons:
  apt:
    sources:
    - git-core
    packages:
    - git
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq docker-ce
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- npm i -g eslint eslint-config-aqua
language: node_js
node_js:
- '8'
install: npm test
script:
- bash ./deploy/deploy.sh
env:
  - secure: FjvkBxWPfVcuXHEzADkcHeIfBJNA5A9qWQTYGz3kwNGtJrx1VJrjhmajWsCIvuyLRT65zzvFgbK2oF2l2SgruMwDPfpkonQOQSM/Tm9gaf76o+gTlkMEMgwfdwX/deNQ62Nt1hJv57jM/kbMrP0IbE+EM6lGFBiGzXOO48DyfAlego5XviwwooBWCFRvEIIM5A1xGHEvzn8TsvR/4fptXyaLNSdxU7lgah1q6vUBKCngav/w6xjQuRt2rreLT5JhE4QOM/jXfulgX9tTlsZxVIKwQ/MJ0D7OlQBqNcfEJo8Mu9v6w1I8W+7gZXGgs/HAWM3fa7ndQMwln6MVJqG59fQPgp/g08BI8CYzUoTtVB6+30UwpO24YmxZyNJpBR96XRp0Rp0/F2KXETKrWFUbTGFHZ5rCg5f6QBbTk699cAbUXzDlq1UGeqrNt9j7IUqT4RwpvDsWgAS4F7LFsH9d63tehzUpOPzIYThTyFmQW5WhtWh+Vu4fJ3ADkCSCCbfduweoBWlLenJkfNEBia6p8f3vb2YiNdV3Fz54DoX6cX+GWsNF5ljFF949yKIxAEJ4hICCYk1zVNl3Oh3+T5C305rRWyukSBdHmt+sfGUsy/r7cujDX4/G020IwNW+ecHFe0LIa3PjbkJG5BSTC9k+FsPdt4AuF5Pq1YwXh/UNtGY=
  - secure: LCCnyJwFhMS+uRso3h7Yz4/ZvFDVeSjObEwzOID0dsHIT+BktTrbQ4bU1XS5vA99E1nHrpeU2kWIOLY6IZ8k746/Fnd2X0rQkPVZ3r9UbdaE6Pj2VV7cfmM5Q9eDIA6ub/aGQMjceU75JnOkuUZ9ElFXHkqaTdWiRrF5BpzQ4pUJvG1IeC4nHMXOITZcbTmM6k5+30mmN431gZExqZya0GUHBSwrNP1FgK9fZwbC6jpysx7P3bcoWn7nY3HIlHKNwvTW4n1yoJXD5bxPiz5TylcDqBGEcPnCBGnAMSSxBMquisIMPKVQJHfxesKNgokvmfH6pNfihHNHQnolKO1oDy7AIU5OvHFH4vqedsDoMurUZ++cz1jSXMXrdgxlv9owaQilNfg2QnhZV1LKfAisGiDx1dOVOQ2/kgtnfl9M0r/jRdLrLrP9n3+d9BQPqgk4DFzSG0EAZTgQhgPTm6fhR+GOOpdbVfG3XoHBTb4E4cFC0mn6V/SNm41NgdumjIV54KFi6mbvPkEQ14b3b8G1aB/Q1I1MNKkrIfWDW4YNPxSWuFDO/2MadqOpOicJjakquWLma+SRY2maQUjAbGNsj7Iy17VamfiH/zHV+FK6TrqD25zMxGCEGYA39qkh04ZdjefSrYQ/B8hgXZO+JXCs/u/xMCWjGZiuh5YYGB+9fy4=